defaults: &defaults
  omniauth:
    github:
      key: <%= ENV['GITHUB_KEY'] || '' %>
      secret: <%= ENV['GITHUB_SECRET'] || '' %>

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
